---

on: [push, pull_request]
jobs:
  check:
    name: Check Commit Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: forkkillet/FkGitCommitMsgStd@test
        with:
          msgs: ${{ toJson(github.event.commits.*.message) }}
